from generatorLib import StickDiagram
from generatorLib import DesignParameters
import copy
import math
from generatorLib import DRC
from generatorLib.generator_models import ViaMet12Met2
from generatorLib.generator_models import ViaPoly2Met1
from generatorLib.generator_models import PMOSWithDummy
from generatorLib.generator_models import ViaMet32Met4
from generatorLib.generator_models import NSubRing
from generatorLib.generator_models import ViaMet22Met3
from generatorLib.generator_models import PSubRing
from generatorLib.generator_models import NMOSWithDummy

class transmission_gate(StickDiagram._StickDiagram):
	def __init__(self, _DesignParameter=None, _Name='transmission_gate'):
		if _DesignParameter != None:
			self._DesignParameter = _DesignParameter
		else:
			self._DesignParameter = dict(_Name=self._NameDeclaration(_Name=_Name), _GDSFile=self._GDSObjDeclaration(_GDSFile=None))
		self._DesignParameter['_Name']['Name'] = _Name

	def _CalculateDesignParameter(self,nmos_via=2,num_of_gate=5,pmos_via=4,output_via=5,subring_addi_space=100,subring_via=2,mos_space=1800,nmos_width=250,channel_length=30,pmos_width=500):
	
		drc = DRC.DRC()
		_Name = self._DesignParameter['_Name']['_Name']
		
		self._DesignParameter['nmos'] = self._SrefElementDeclaration(_DesignObj=NMOSWithDummy._NMOS(_Name='nmosIn{}'.format(_Name)))[0]
		self._DesignParameter['nmos']['_DesignObj']._CalculateNMOSDesignParameter(**dict(_NMOSNumberofGate=num_of_gate, _NMOSChannelWidth=nmos_width, _NMOSChannellength=channel_length, _NMOSDummy=True, _GateSpacing=100, _XVT='SLVT'))
		self._DesignParameter['nmos']['_XYCoordinates'] = [[0.0, 0.0]]
		self._DesignParameter['pmos'] = self._SrefElementDeclaration(_DesignObj=PMOSWithDummy._PMOS(_Name='pmosIn{}'.format(_Name)))[0]
		self._DesignParameter['pmos']['_DesignObj']._CalculatePMOSDesignParameter(**dict(_PMOSNumberofGate=num_of_gate, _PMOSChannelWidth=pmos_width, _PMOSChannellength=channel_length, _PMOSDummy=True, _GateSpacing=100, _XVT='SLVT'))
		self._DesignParameter['pmos']['_XYCoordinates'] = [[0, mos_space]]
		self._DesignParameter['nmos_gate_via'] = self._SrefElementDeclaration(_DesignObj=ViaPoly2Met1._ViaPoly2Met1(_Name='nmos_gate_viaIn{}'.format(_Name)))[0]
		self._DesignParameter['nmos_gate_via']['_DesignObj']._CalculateViaPoly2Met1DesignParameter(**dict(_ViaPoly2Met1NumberOfCOX=int((((((self._DesignParameter['nmos']['_XYCoordinates'][0][0] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][(- 1)][0]) - (self._DesignParameter['nmos']['_XYCoordinates'][0][0] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0])) + drc._CoMinSpace) - (2 * drc._CoMinEnclosureByPO)) / (drc._CoMinWidth + drc._CoMinSpace))), _ViaPoly2Met1NumberOfCOY=1))
		self._DesignParameter['nmos_gate_via']['_XYCoordinates'] = [[self._DesignParameter['nmos']['_XYCoordinates'][0][0], max(((((self._DesignParameter['nmos']['_XYCoordinates'][0][1] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) + (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2)) + (self._DesignParameter['nmos_gate_via']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2)) + drc._PolygateMinSpace), ((((self._DesignParameter['nmos']['_XYCoordinates'][0][1] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) + (self._DesignParameter['nmos_gate_via']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) + drc._Metal1MinSpace))]]
		self._DesignParameter['POLY_path_21'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _Width=60)
		self._DesignParameter['POLY_path_21']['_XYCoordinates'] = [[[(self._DesignParameter['nmos']['_XYCoordinates'][0][0] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]), self._DesignParameter['nmos_gate_via']['_XYCoordinates'][0][1]], [(self._DesignParameter['nmos']['_XYCoordinates'][0][0] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][(- 1)][0]), self._DesignParameter['nmos_gate_via']['_XYCoordinates'][0][1]]]]
		path_list = []
		if (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0] == self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][(- 1)][0]):
		    mode = 'horizontal'
		    _width = self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_XWidth']
		elif (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1] == self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][(- 1)][1]):
		    mode = 'vertical'
		    _width = self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_XWidth']
		else:
		    print('Invalid Target Input')
		if (mode == 'vertical'):
		    xy_with_offset = []
		    target_y_value = ((self._DesignParameter['nmos_gate_via']['_XYCoordinates'][0][1] + self._DesignParameter['nmos_gate_via']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) + (self._DesignParameter['nmos_gate_via']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2))
		    for i in range(len(self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'])):
		        xy_with_offset.append([(x + y) for (x, y) in zip([(0 + self._DesignParameter['nmos']['_XYCoordinates'][0][0]), (0 + self._DesignParameter['nmos']['_XYCoordinates'][0][1])], self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][i])])
		    for i in range(len(xy_with_offset)):
		        path_list.append([xy_with_offset[i], [xy_with_offset[i][0], target_y_value]])
		elif (mode == 'horizontal'):
		    xy_with_offset = []
		    target_x_value = (self._DesignParameter['nmos_gate_via']['_XYCoordinates'][0][0] + self._DesignParameter['nmos_gate_via']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0])
		    for i in range(len(self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'])):
		        xy_with_offset.append([(x + y) for (x, y) in zip([(0 + self._DesignParameter['nmos']['_XYCoordinates'][0][0]), (0 + self._DesignParameter['nmos']['_XYCoordinates'][0][1])], self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][i])])
		    for i in range(len(xy_with_offset)):
		        path_list.append([xy_with_offset[i], [target_x_value, xy_with_offset[i][1]]])
		self._DesignParameter['nmos_gate_poly_array'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _Width=_width)
		self._DesignParameter['nmos_gate_poly_array']['_XYCoordinates'] = path_list
		self._DesignParameter['pmos_gate_via'] = self._SrefElementDeclaration(_DesignObj=ViaPoly2Met1._ViaPoly2Met1(_Name='pmos_gate_viaIn{}'.format(_Name)))[0]
		self._DesignParameter['pmos_gate_via']['_DesignObj']._CalculateViaPoly2Met1DesignParameter(**dict(_ViaPoly2Met1NumberOfCOX=int((((((self._DesignParameter['nmos']['_XYCoordinates'][0][0] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][(- 1)][0]) - (self._DesignParameter['nmos']['_XYCoordinates'][0][0] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0])) + drc._CoMinSpace) - (2 * drc._CoMinEnclosureByPO)) / (drc._CoMinWidth + drc._CoMinSpace))), _ViaPoly2Met1NumberOfCOY=1))
		self._DesignParameter['pmos_gate_via']['_XYCoordinates'] = [[self._DesignParameter['pmos']['_XYCoordinates'][0][0], min(((((self._DesignParameter['pmos']['_XYCoordinates'][0][1] + self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) - (self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2)) - (self._DesignParameter['pmos_gate_via']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2)) - drc._PolygateMinSpace), ((((self._DesignParameter['pmos']['_XYCoordinates'][0][1] + self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) - (self._DesignParameter['pmos_gate_via']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) - drc._Metal1MinSpace))]]
		self._DesignParameter['POLY_path_0'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _Width=60)
		self._DesignParameter['POLY_path_0']['_XYCoordinates'] = [[[(self._DesignParameter['pmos']['_XYCoordinates'][0][0] + self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]), self._DesignParameter['pmos_gate_via']['_XYCoordinates'][0][1]], [(self._DesignParameter['pmos']['_XYCoordinates'][0][0] + self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][(- 1)][0]), self._DesignParameter['pmos_gate_via']['_XYCoordinates'][0][1]]]]
		path_list = []
		if (self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0] == self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][(- 1)][0]):
		    mode = 'horizontal'
		    _width = self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_XWidth']
		elif (self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1] == self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][(- 1)][1]):
		    mode = 'vertical'
		    _width = self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_XWidth']
		else:
		    print('Invalid Target Input')
		if (mode == 'vertical'):
		    xy_with_offset = []
		    target_y_value = ((self._DesignParameter['pmos_gate_via']['_XYCoordinates'][0][1] + self._DesignParameter['pmos_gate_via']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) - (self._DesignParameter['pmos_gate_via']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2))
		    for i in range(len(self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'])):
		        xy_with_offset.append([(x + y) for (x, y) in zip([(0 + self._DesignParameter['pmos']['_XYCoordinates'][0][0]), (0 + self._DesignParameter['pmos']['_XYCoordinates'][0][1])], self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][i])])
		    for i in range(len(xy_with_offset)):
		        path_list.append([xy_with_offset[i], [xy_with_offset[i][0], target_y_value]])
		elif (mode == 'horizontal'):
		    xy_with_offset = []
		    target_x_value = (self._DesignParameter['pmos_gate_via']['_XYCoordinates'][0][0] + self._DesignParameter['pmos_gate_via']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0])
		    for i in range(len(self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'])):
		        xy_with_offset.append([(x + y) for (x, y) in zip([(0 + self._DesignParameter['pmos']['_XYCoordinates'][0][0]), (0 + self._DesignParameter['pmos']['_XYCoordinates'][0][1])], self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][i])])
		    for i in range(len(xy_with_offset)):
		        path_list.append([xy_with_offset[i], [target_x_value, xy_with_offset[i][1]]])
		self._DesignParameter['pmos_gate_poly_array'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _Width=_width)
		self._DesignParameter['pmos_gate_poly_array']['_XYCoordinates'] = path_list
		XYList = []
		xy_offset = (0, (- int(((drc._VIAxMinWidth + drc._VIAxMinSpace) / 4))))
		for i in range(len(self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'])):
		    if ((i % 2) == 0):
		        XYList.append([((x + y) + z) for (x, y, z) in zip([(0 + self._DesignParameter['nmos']['_XYCoordinates'][0][0]), (0 + self._DesignParameter['nmos']['_XYCoordinates'][0][1])], self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'][i], xy_offset)])
		self._DesignParameter['nmos_source_via12'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='nmos_source_via12In{}'.format(_Name)))[0]
		self._DesignParameter['nmos_source_via12']['_DesignObj']._CalculateViaMet12Met2DesignParameterMinimumEnclosureX(**dict(_ViaMet12Met2NumberOfCOX=1, _ViaMet12Met2NumberOfCOY=nmos_via))
		self._DesignParameter['nmos_source_via12']['_XYCoordinates'] = XYList
		XYList = []
		xy_offset = (0, 0)
		for i in range(len(self._DesignParameter['nmos_source_via12']['_XYCoordinates'])):
		    XYList.append([((x + y) + z) for (x, y, z) in zip([0, 0], self._DesignParameter['nmos_source_via12']['_XYCoordinates'][i], xy_offset)])
		self._DesignParameter['nmos_source_via_23'] = self._SrefElementDeclaration(_DesignObj=ViaMet22Met3._ViaMet22Met3(_Name='nmos_source_via_23In{}'.format(_Name)))[0]
		self._DesignParameter['nmos_source_via_23']['_DesignObj']._CalculateViaMet22Met3DesignParameterMinimumEnclosureX(**dict(_ViaMet22Met3NumberOfCOX=1, _ViaMet22Met3NumberOfCOY=nmos_via))
		self._DesignParameter['nmos_source_via_23']['_XYCoordinates'] = XYList
		XYList = []
		xy_offset = (0, int(((drc._VIAxMinWidth + drc._VIAxMinSpace) / 4)))
		for i in range(len(self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'])):
		    if ((i % 2) == 0):
		        XYList.append([((x + y) + z) for (x, y, z) in zip([(0 + self._DesignParameter['pmos']['_XYCoordinates'][0][0]), (0 + self._DesignParameter['pmos']['_XYCoordinates'][0][1])], self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'][i], xy_offset)])
		self._DesignParameter['pmos_source_via12'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='pmos_source_via12In{}'.format(_Name)))[0]
		self._DesignParameter['pmos_source_via12']['_DesignObj']._CalculateViaMet12Met2DesignParameterMinimumEnclosureX(**dict(_ViaMet12Met2NumberOfCOX=1, _ViaMet12Met2NumberOfCOY=pmos_via))
		self._DesignParameter['pmos_source_via12']['_XYCoordinates'] = XYList
		XYList = []
		xy_offset = (0, 0)
		for i in range(len(self._DesignParameter['pmos_source_via12']['_XYCoordinates'])):
		    XYList.append([((x + y) + z) for (x, y, z) in zip([0, 0], self._DesignParameter['pmos_source_via12']['_XYCoordinates'][i], xy_offset)])
		self._DesignParameter['pmos_source_via23'] = self._SrefElementDeclaration(_DesignObj=ViaMet22Met3._ViaMet22Met3(_Name='pmos_source_via23In{}'.format(_Name)))[0]
		self._DesignParameter['pmos_source_via23']['_DesignObj']._CalculateViaMet22Met3DesignParameterMinimumEnclosureX(**dict(_ViaMet22Met3NumberOfCOX=1, _ViaMet22Met3NumberOfCOY=pmos_via))
		self._DesignParameter['pmos_source_via23']['_XYCoordinates'] = XYList
		XYList = []
		xy_offset = (0, int(((drc._VIAxMinWidth + drc._VIAxMinSpace) / 4)))
		for i in range(len(self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'])):
		    if ((i % 2) == 1):
		        XYList.append([((x + y) + z) for (x, y, z) in zip([(0 + self._DesignParameter['nmos']['_XYCoordinates'][0][0]), (0 + self._DesignParameter['nmos']['_XYCoordinates'][0][1])], self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][i], xy_offset)])
		self._DesignParameter['nmos_drain_via'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='nmos_drain_viaIn{}'.format(_Name)))[0]
		self._DesignParameter['nmos_drain_via']['_DesignObj']._CalculateViaMet12Met2DesignParameterMinimumEnclosureX(**dict(_ViaMet12Met2NumberOfCOX=1, _ViaMet12Met2NumberOfCOY=nmos_via))
		self._DesignParameter['nmos_drain_via']['_XYCoordinates'] = XYList
		XYList = []
		xy_offset = (0, (- int(((drc._VIAxMinWidth + drc._VIAxMinSpace) / 4))))
		for i in range(len(self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'])):
		    if ((i % 2) == 1):
		        XYList.append([((x + y) + z) for (x, y, z) in zip([(0 + self._DesignParameter['pmos']['_XYCoordinates'][0][0]), (0 + self._DesignParameter['pmos']['_XYCoordinates'][0][1])], self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][i], xy_offset)])
		self._DesignParameter['pmos_drain_via'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='pmos_drain_viaIn{}'.format(_Name)))[0]
		self._DesignParameter['pmos_drain_via']['_DesignObj']._CalculateViaMet12Met2DesignParameterMinimumEnclosureX(**dict(_ViaMet12Met2NumberOfCOX=1, _ViaMet12Met2NumberOfCOY=pmos_via))
		self._DesignParameter['pmos_drain_via']['_XYCoordinates'] = XYList
		path_list = []
		if (self._DesignParameter['nmos_drain_via']['_XYCoordinates'][0][0] == self._DesignParameter['nmos_drain_via']['_XYCoordinates'][(- 1)][0]):
		    mode = 'horizontal'
		    _width = self._DesignParameter['nmos_drain_via']['_DesignObj']._DesignParameter['_Met2Layer']['_XWidth']
		elif (self._DesignParameter['nmos_drain_via']['_XYCoordinates'][0][1] == self._DesignParameter['nmos_drain_via']['_XYCoordinates'][(- 1)][1]):
		    mode = 'vertical'
		    _width = self._DesignParameter['nmos_drain_via']['_DesignObj']._DesignParameter['_Met2Layer']['_XWidth']
		else:
		    print('Invalid Target Input')
		if (mode == 'vertical'):
		    xy_with_offset = []
		    target_y_value = (0 + self._DesignParameter['pmos_drain_via']['_XYCoordinates'][0][1])
		    for i in range(len(self._DesignParameter['nmos_drain_via']['_XYCoordinates'])):
		        xy_with_offset.append([(x + y) for (x, y) in zip([0, 0], self._DesignParameter['nmos_drain_via']['_XYCoordinates'][i])])
		    for i in range(len(xy_with_offset)):
		        path_list.append([xy_with_offset[i], [xy_with_offset[i][0], target_y_value]])
		elif (mode == 'horizontal'):
		    xy_with_offset = []
		    target_x_value = (0 + self._DesignParameter['pmos_drain_via']['_XYCoordinates'][0][0])
		    for i in range(len(self._DesignParameter['nmos_drain_via']['_XYCoordinates'])):
		        xy_with_offset.append([(x + y) for (x, y) in zip([0, 0], self._DesignParameter['nmos_drain_via']['_XYCoordinates'][i])])
		    for i in range(len(xy_with_offset)):
		        path_list.append([xy_with_offset[i], [target_x_value, xy_with_offset[i][1]]])
		self._DesignParameter['drain_routing'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL2'][0], _Datatype=DesignParameters._LayerMapping['METAL2'][1], _Width=_width)
		self._DesignParameter['drain_routing']['_XYCoordinates'] = path_list
		XYList = []
		xy_offset = (0, (int(((((self._DesignParameter['nmos_drain_via']['_XYCoordinates'][0][1] + self._DesignParameter['nmos_drain_via']['_DesignObj']._DesignParameter['_Met2Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['nmos_drain_via']['_DesignObj']._DesignParameter['_Met2Layer']['_YWidth'] / 2)) + ((self._DesignParameter['pmos_drain_via']['_XYCoordinates'][0][1] + self._DesignParameter['pmos_drain_via']['_DesignObj']._DesignParameter['_Met2Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['pmos_drain_via']['_DesignObj']._DesignParameter['_Met2Layer']['_YWidth'] / 2))) / 2)) - self._DesignParameter['nmos_drain_via']['_XYCoordinates'][0][1]))
		for i in range(len(self._DesignParameter['nmos_drain_via']['_XYCoordinates'])):
		    XYList.append([((x + y) + z) for (x, y, z) in zip([0, 0], self._DesignParameter['nmos_drain_via']['_XYCoordinates'][i], xy_offset)])
		self._DesignParameter['output_via23_array'] = self._SrefElementDeclaration(_DesignObj=ViaMet22Met3._ViaMet22Met3(_Name='output_via23_arrayIn{}'.format(_Name)))[0]
		self._DesignParameter['output_via23_array']['_DesignObj']._CalculateViaMet22Met3DesignParameterMinimumEnclosureX(**dict(_ViaMet22Met3NumberOfCOX=1, _ViaMet22Met3NumberOfCOY=output_via))
		self._DesignParameter['output_via23_array']['_XYCoordinates'] = XYList
		XYList = []
		xy_offset = [0, 0]
		for i in range(len(self._DesignParameter['output_via23_array']['_XYCoordinates'])):
		    XYList.append([((x + y) + z) for (x, y, z) in zip([0, 0], self._DesignParameter['output_via23_array']['_XYCoordinates'][i], xy_offset)])
		self._DesignParameter['output_via34_array'] = self._SrefElementDeclaration(_DesignObj=ViaMet32Met4._ViaMet32Met4(_Name='output_via34_arrayIn{}'.format(_Name)))[0]
		self._DesignParameter['output_via34_array']['_DesignObj']._CalculateViaMet32Met4DesignParameterMinimumEnclosureX(**dict(_ViaMet32Met4NumberOfCOX=1, _ViaMet32Met4NumberOfCOY=output_via))
		self._DesignParameter['output_via34_array']['_XYCoordinates'] = XYList
		self._DesignParameter['METAL4_boundary_9'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL4'][0], _Datatype=DesignParameters._LayerMapping['METAL4'][1], _XWidth=(self._DesignParameter['output_via34_array']['_XYCoordinates'][(- 1)][0] - self._DesignParameter['output_via34_array']['_XYCoordinates'][0][0]), _YWidth=(((self._DesignParameter['output_via34_array']['_XYCoordinates'][0][1] + self._DesignParameter['output_via34_array']['_DesignObj']._DesignParameter['_Met4Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['output_via34_array']['_DesignObj']._DesignParameter['_Met4Layer']['_YWidth'] / 2)) - ((self._DesignParameter['output_via34_array']['_XYCoordinates'][0][1] + self._DesignParameter['output_via34_array']['_DesignObj']._DesignParameter['_Met4Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['output_via34_array']['_DesignObj']._DesignParameter['_Met4Layer']['_YWidth'] / 2))))
		self._DesignParameter['METAL4_boundary_9']['_XYCoordinates'] = [[((self._DesignParameter['output_via34_array']['_XYCoordinates'][(- 1)][0] + self._DesignParameter['output_via34_array']['_XYCoordinates'][0][0]) / 2), self._DesignParameter['output_via34_array']['_XYCoordinates'][0][1]]]
		self._DesignParameter['nmos_input_via12'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='nmos_input_via12In{}'.format(_Name)))[0]
		self._DesignParameter['nmos_input_via12']['_DesignObj']._CalculateViaMet12Met2DesignParameterMinimumEnclosureY(**dict(_ViaMet12Met2NumberOfCOX=2, _ViaMet12Met2NumberOfCOY=1))
		self._DesignParameter['nmos_input_via12']['_XYCoordinates'] = [[int(((((self._DesignParameter['output_via23_array']['_XYCoordinates'][0][0] + self._DesignParameter['output_via23_array']['_DesignObj']._DesignParameter['_Met2Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['output_via23_array']['_DesignObj']._DesignParameter['_Met2Layer']['_XWidth'] / 2)) - (self._DesignParameter['nmos_input_via12']['_DesignObj']._DesignParameter['_Met2Layer']['_XWidth'] / 2)) - drc._MetalxMinSpace2)), self._DesignParameter['nmos_gate_via']['_XYCoordinates'][0][1]]]
		self._DesignParameter['pmos_input_via12'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='pmos_input_via12In{}'.format(_Name)))[0]
		self._DesignParameter['pmos_input_via12']['_DesignObj']._CalculateViaMet12Met2DesignParameterMinimumEnclosureY(**dict(_ViaMet12Met2NumberOfCOX=2, _ViaMet12Met2NumberOfCOY=1))
		self._DesignParameter['pmos_input_via12']['_XYCoordinates'] = [[math.ceil(((((self._DesignParameter['output_via23_array']['_XYCoordinates'][0][0] + self._DesignParameter['output_via23_array']['_DesignObj']._DesignParameter['_Met2Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['output_via23_array']['_DesignObj']._DesignParameter['_Met2Layer']['_XWidth'] / 2)) - (self._DesignParameter['pmos_input_via12']['_DesignObj']._DesignParameter['_Met2Layer']['_XWidth'] / 2)) - drc._MetalxMinSpace2)), self._DesignParameter['pmos_gate_via']['_XYCoordinates'][0][1]]]
		self._DesignParameter['METAL1_path_0'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1'][0], _Datatype=DesignParameters._LayerMapping['METAL1'][1], _Width=max(self._DesignParameter['nmos_gate_via']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'], self._DesignParameter['nmos_input_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth']))
		self._DesignParameter['METAL1_path_0']['_XYCoordinates'] = [[[(+ self._DesignParameter['nmos_gate_via']['_XYCoordinates'][0][0]), (+ self._DesignParameter['nmos_gate_via']['_XYCoordinates'][0][1])], [((self._DesignParameter['nmos_input_via12']['_XYCoordinates'][0][0] + self._DesignParameter['nmos_input_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['nmos_input_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)), self._DesignParameter['nmos_gate_via']['_XYCoordinates'][0][1]]]]
		self._DesignParameter['NMOSSubringInResistorBank_0'] = self._SrefElementDeclaration(_DesignObj=PSubRing.PSubRing(_Name='NMOSSubringInResistorBank_0In{}'.format(_Name)))[0]
		self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._CalculateDesignParameter(**dict(width=(max((((self._DesignParameter['nmos']['_XYCoordinates'][0][0] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][(- 1)][0]) + (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_XWidth'] / 2)) + drc._PolygateMinSpace2OD), (((self._DesignParameter['nmos']['_XYCoordinates'][0][0] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][(- 1)][0]) + (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)) + drc._Metal1MinSpace)) - (((self._DesignParameter['nmos_input_via12']['_XYCoordinates'][0][0] + self._DesignParameter['nmos_input_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['nmos_input_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)) - drc._Metal1MinSpace)), contact=subring_via, height=((((self._DesignParameter['nmos_gate_via']['_XYCoordinates'][0][1] + self._DesignParameter['nmos_gate_via']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['nmos_gate_via']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) - min((((self._DesignParameter['nmos']['_XYCoordinates'][0][1] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) - drc._Metal1MinSpace), (((self._DesignParameter['nmos']['_XYCoordinates'][0][1] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_ODLayer']['_XYCoordinates'][0][1]) - (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_ODLayer']['_YWidth'] / 2)) - drc._OdMinSpace))) + drc._Metal1MinSpace)))
		self._DesignParameter['NMOSSubringInResistorBank_0']['_XYCoordinates'] = [[((max((((self._DesignParameter['nmos']['_XYCoordinates'][0][0] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][(- 1)][0]) + (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_XWidth'] / 2)) + drc._PolygateMinSpace2OD), (((self._DesignParameter['nmos']['_XYCoordinates'][0][0] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][(- 1)][0]) + (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)) + drc._Metal1MinSpace)) + (((self._DesignParameter['nmos_input_via12']['_XYCoordinates'][0][0] + self._DesignParameter['nmos_input_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['nmos_input_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)) - drc._Metal1MinSpace)) / 2), ((((self._DesignParameter['nmos_gate_via']['_XYCoordinates'][0][1] + self._DesignParameter['nmos_gate_via']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['nmos_gate_via']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) + ((self._DesignParameter['nmos']['_XYCoordinates'][0][1] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) - (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2))) / 2)]]
		self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._CalculateDesignParameter(**dict(width=(((max((((self._DesignParameter['nmos']['_XYCoordinates'][0][0] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][(- 1)][0]) + (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_XWidth'] / 2)) + drc._PolygateMinSpace2OD), (((self._DesignParameter['nmos']['_XYCoordinates'][0][0] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][(- 1)][0]) + (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)) + drc._Metal1MinSpace)) - (((self._DesignParameter['nmos_input_via12']['_XYCoordinates'][0][0] + self._DesignParameter['nmos_input_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['nmos_input_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)) - drc._Metal1MinSpace)) + subring_addi_space) + self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['met_right']['_XWidth']), contact=subring_via, height=((((((self._DesignParameter['nmos_gate_via']['_XYCoordinates'][0][1] + self._DesignParameter['nmos_gate_via']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['nmos_gate_via']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) - min((((self._DesignParameter['nmos']['_XYCoordinates'][0][1] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) - drc._Metal1MinSpace), (((self._DesignParameter['nmos']['_XYCoordinates'][0][1] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_ODLayer']['_XYCoordinates'][0][1]) - (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_ODLayer']['_YWidth'] / 2)) - drc._OdMinSpace))) + drc._Metal1MinSpace) + self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['met_top']['_YWidth']) + subring_addi_space)))
		self._DesignParameter['PMOSSubringInResistorBank_0'] = self._SrefElementDeclaration(_DesignObj=NSubRing.NSubRing(_Name='PMOSSubringInResistorBank_0In{}'.format(_Name)))[0]
		self._DesignParameter['PMOSSubringInResistorBank_0']['_DesignObj']._CalculateDesignParameter(**dict(height=((self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['met_top']['_YWidth'] + subring_addi_space) + (((drc._PolygateMinSpace2OD + ((self._DesignParameter['pmos']['_XYCoordinates'][0][1] + self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) + (self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2))) - ((self._DesignParameter['pmos_gate_via']['_XYCoordinates'][0][1] + self._DesignParameter['pmos_gate_via']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['pmos_gate_via']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))) + drc._Metal1MinSpace)), width=(((max((((self._DesignParameter['nmos']['_XYCoordinates'][0][0] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][(- 1)][0]) + (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_XWidth'] / 2)) + drc._PolygateMinSpace2OD), (((self._DesignParameter['nmos']['_XYCoordinates'][0][0] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][(- 1)][0]) + (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)) + drc._Metal1MinSpace)) - (((self._DesignParameter['nmos_input_via12']['_XYCoordinates'][0][0] + self._DesignParameter['nmos_input_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['nmos_input_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)) - drc._Metal1MinSpace)) + subring_addi_space) + self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['met_right']['_XWidth']), contact=subring_via))
		self._DesignParameter['PMOSSubringInResistorBank_0']['_XYCoordinates'] = [[self._DesignParameter['NMOSSubringInResistorBank_0']['_XYCoordinates'][0][0], ((((self._DesignParameter['pmos']['_XYCoordinates'][0][1] + self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) + (self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2)) + ((self._DesignParameter['pmos_gate_via']['_XYCoordinates'][0][1] + self._DesignParameter['pmos_gate_via']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['pmos_gate_via']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))) / 2)]]
		self._DesignParameter['pmos_input_rou'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1'][0], _Datatype=DesignParameters._LayerMapping['METAL1'][1], _Width=self._DesignParameter['pmos_gate_via']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'])
		self._DesignParameter['pmos_input_rou']['_XYCoordinates'] = [[[(+ self._DesignParameter['pmos_gate_via']['_XYCoordinates'][0][0]), (+ self._DesignParameter['pmos_gate_via']['_XYCoordinates'][0][1])], [((self._DesignParameter['pmos_input_via12']['_XYCoordinates'][0][0] + self._DesignParameter['pmos_input_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['pmos_input_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)), self._DesignParameter['pmos_gate_via']['_XYCoordinates'][0][1]]]]
		self._DesignParameter['METAL3_path_0'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL3'][0], _Datatype=DesignParameters._LayerMapping['METAL3'][1], _Width=self._DesignParameter['nmos_source_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'])
		self._DesignParameter['METAL3_path_0']['_XYCoordinates'] = [[[(+ ((self._DesignParameter['nmos_source_via12']['_XYCoordinates'][0][0] + self._DesignParameter['nmos_source_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['nmos_source_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2))), (+ (self._DesignParameter['nmos_source_via12']['_XYCoordinates'][0][1] + self._DesignParameter['nmos_source_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]))], [((self._DesignParameter['NMOSSubringInResistorBank_0']['_XYCoordinates'][0][0] + self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['met_right']['_XYCoordinates'][0][0]) + (self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['met_right']['_XWidth'] / 2)), (self._DesignParameter['nmos_source_via12']['_XYCoordinates'][0][1] + self._DesignParameter['nmos_source_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1])]]]
		self._DesignParameter['METAL3_path_0_copy'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL3'][0], _Datatype=DesignParameters._LayerMapping['METAL3'][1], _Width=self._DesignParameter['pmos_source_via23']['_DesignObj']._DesignParameter['_Met3Layer']['_YWidth'])
		self._DesignParameter['METAL3_path_0_copy']['_XYCoordinates'] = [[[(+ ((self._DesignParameter['pmos_source_via23']['_XYCoordinates'][0][0] + self._DesignParameter['pmos_source_via23']['_DesignObj']._DesignParameter['_Met3Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['pmos_source_via23']['_DesignObj']._DesignParameter['_Met3Layer']['_XWidth'] / 2))), (+ (self._DesignParameter['pmos_source_via23']['_XYCoordinates'][0][1] + self._DesignParameter['pmos_source_via23']['_DesignObj']._DesignParameter['_Met3Layer']['_XYCoordinates'][0][1]))], [((self._DesignParameter['PMOSSubringInResistorBank_0']['_XYCoordinates'][0][0] + self._DesignParameter['PMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['met_right']['_XYCoordinates'][0][0]) + (self._DesignParameter['PMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['met_right']['_XWidth'] / 2)), (self._DesignParameter['pmos_source_via23']['_XYCoordinates'][0][1] + self._DesignParameter['pmos_source_via23']['_DesignObj']._DesignParameter['_Met3Layer']['_XYCoordinates'][0][1])]]]
		self._DesignParameter['nw_add'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['NWELL'][0], _Datatype=DesignParameters._LayerMapping['NWELL'][1], _XWidth=(((max((((self._DesignParameter['nmos']['_XYCoordinates'][0][0] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][(- 1)][0]) + (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_XWidth'] / 2)) + drc._PolygateMinSpace2OD), (((self._DesignParameter['nmos']['_XYCoordinates'][0][0] + self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][(- 1)][0]) + (self._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)) + drc._Metal1MinSpace)) - (((self._DesignParameter['nmos_input_via12']['_XYCoordinates'][0][0] + self._DesignParameter['nmos_input_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['nmos_input_via12']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)) - drc._Metal1MinSpace)) + subring_addi_space) + self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['met_right']['_XWidth']), _YWidth=((self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['met_top']['_YWidth'] + subring_addi_space) + (((drc._PolygateMinSpace2OD + ((self._DesignParameter['pmos']['_XYCoordinates'][0][1] + self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1]) + (self._DesignParameter['pmos']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'] / 2))) - ((self._DesignParameter['pmos_gate_via']['_XYCoordinates'][0][1] + self._DesignParameter['pmos_gate_via']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['pmos_gate_via']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))) + drc._Metal1MinSpace)))
		self._DesignParameter['nw_add']['_XYCoordinates'] = [[(+ self._DesignParameter['PMOSSubringInResistorBank_0']['_XYCoordinates'][0][0]), (+ self._DesignParameter['PMOSSubringInResistorBank_0']['_XYCoordinates'][0][1])]]
		self._DesignParameter['via2to3_n'] = self._SrefElementDeclaration(_DesignObj=ViaMet22Met3._ViaMet22Met3(_Name='via2to3_nIn{}'.format(_Name)))[0]
		self._DesignParameter['via2to3_n']['_DesignObj']._CalculateViaMet22Met3DesignParameterMinimumEnclosureY(**dict(_ViaMet22Met3NumberOfCOX=int((((self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['met_right']['_XWidth'] + drc._VIAxMinSpace2) - (2 * drc._VIAxMinEnclosureByMetxTwoOppositeSide)) / (drc._VIAxMinWidth + drc._VIAxMinSpace2))), _ViaMet22Met3NumberOfCOY=int(((self._DesignParameter['nmos_source_via_23']['_DesignObj']._DesignParameter['_Met3Layer']['_YWidth'] + drc._VIAxMinWidth) / (drc._VIAxMinWidth + drc._VIAxMinSpace)))))
		self._DesignParameter['via2to3_n']['_XYCoordinates'] = [[(self._DesignParameter['NMOSSubringInResistorBank_0']['_XYCoordinates'][0][0] + self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['met_right']['_XYCoordinates'][0][0]), self._DesignParameter['nmos_source_via_23']['_XYCoordinates'][(- 1)][1]]]
		self._DesignParameter['via2to3_p'] = self._SrefElementDeclaration(_DesignObj=ViaMet22Met3._ViaMet22Met3(_Name='via2to3_pIn{}'.format(_Name)))[0]
		self._DesignParameter['via2to3_p']['_DesignObj']._CalculateViaMet22Met3DesignParameterMinimumEnclosureY(**dict(_ViaMet22Met3NumberOfCOX=int((((self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['met_right']['_XWidth'] + drc._VIAxMinSpace) - (2 * drc._VIAxMinEnclosureByMetxTwoOppositeSide)) / (drc._VIAxMinWidth + drc._VIAxMinSpace))), _ViaMet22Met3NumberOfCOY=int(((self._DesignParameter['pmos_source_via23']['_DesignObj']._DesignParameter['_Met3Layer']['_YWidth'] + drc._VIAxMinWidth) / (drc._VIAxMinWidth + drc._VIAxMinSpace)))))
		self._DesignParameter['via2to3_p']['_XYCoordinates'] = [[(self._DesignParameter['PMOSSubringInResistorBank_0']['_XYCoordinates'][0][0] + self._DesignParameter['PMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['met_right']['_XYCoordinates'][0][0]), self._DesignParameter['pmos_source_via23']['_XYCoordinates'][(- 1)][1]]]
		self._DesignParameter['METAL2_path_0'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL2'][0], _Datatype=DesignParameters._LayerMapping['METAL2'][1], _Width=max(self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['met_right']['_XWidth'], self._DesignParameter['via2to3_n']['_DesignObj']._DesignParameter['_Met3Layer']['_XWidth']))
		self._DesignParameter['METAL2_path_0']['_XYCoordinates'] = [[[(+ (self._DesignParameter['via2to3_n']['_XYCoordinates'][0][0] + self._DesignParameter['via2to3_n']['_DesignObj']._DesignParameter['_Met2Layer']['_XYCoordinates'][0][0])), (+ ((self._DesignParameter['via2to3_n']['_XYCoordinates'][0][1] + self._DesignParameter['via2to3_n']['_DesignObj']._DesignParameter['_Met2Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['via2to3_n']['_DesignObj']._DesignParameter['_Met2Layer']['_YWidth'] / 2)))], [(self._DesignParameter['via2to3_n']['_XYCoordinates'][0][0] + self._DesignParameter['via2to3_n']['_DesignObj']._DesignParameter['_Met2Layer']['_XYCoordinates'][0][0]), ((self._DesignParameter['via2to3_p']['_XYCoordinates'][0][1] + self._DesignParameter['via2to3_p']['_DesignObj']._DesignParameter['_Met2Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['via2to3_p']['_DesignObj']._DesignParameter['_Met2Layer']['_YWidth'] / 2))]]]
		